### ISSUE TITLE
Cannot sign-in via sign-in modal , missing password field

### ISSUE THREAD

**Issue by connoratrug** [molgenis/molgenis-emx2#1514]
**What version of EMX2 are you using (see footer)**
8.112.0

**Describe the bug**
Sign in form is missing passwords field

**To Reproduce**
1. Go to 8.112.x server
2. Click on sign-in
3. password field is missing

**Expected behavior**
password field is shown

**Comment by connoratrug** [comment]
null pointer

```
vue.runtime.esm.js:1897 TypeError: Cannot read properties of null (reading 'length')
    at a.stringError (molgenis-components.es.js:2690:50)
    at rr.get (vue.runtime.esm.js:4495:25)
    at rr.evaluate (vue.runtime.esm.js:4597:21)
    at a.stringError (vue.runtime.esm.js:4851:17)
    at a.tr (molgenis-components.es.js:2638:23)
    at e._render (vue.runtime.esm.js:3569:22)
    at a.r (vue.runtime.esm.js:4081:21)
    at rr.get (vue.runtime.esm.js:4495:25)
    at new rr (vue.runtime.esm.js:4484:12)
    at Ln (vue.runtime.esm.js:4088:3)
