### ISSUE TITLE
make emx2 more resilient with postgresql hiccups

### ISSUE THREAD

**Issue by erikschaberg** [molgenis/molgenis-emx2#1886]
**What version of EMX2 are you using (see footer)**
8.121.2

**Describe the bug**
emx2 was in a pickle in production, and a restart of emx2 did not help, it looked as if the postgresql server was in a strange state.
	at org.molgenis.emx2.sql.SqlDatabase.<init>(SqlDatabase.java:94)
	at org.molgenis.emx2.RunMolgenisEmx2.main(RunMolgenisEmx2.java:29)
	Suppressed: java.lang.NullPointerException: Cannot invoke "java.sql.Connection.close()" because "connection" is null
		at org.jooq.impl.DataSourceConnectionProvider.release(DataSourceConnectionProvider.java:97)
		at org.molgenis.emx2.sql.SqlUserAwareConnectionProvider.acquire(SqlUserAwareConnectionProvider.java:37)
		at org.jooq.impl.DefaultTransactionProvider.connection(DefaultTransactionProvider.java:131)
		at org.jooq.impl.DefaultTransactionProvider.brace(DefaultTransactionProvider.java:218)
		at org.jooq.impl.DefaultTransactionProvider.rollback(DefaultTransactionProvider.java:209)
		at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:576)
		... 10 more
we solved it by restarting the postgresql first and then an extra restart of emx2.

**To Reproduce**
hard to reproduce

**Expected behavior**
I would be nice if a short posgresql hiccup would not hang emx2. 

**Screenshots**
N.a.

**Desktop (please complete the following information):**
n.a.

**Smartphone (please complete the following information):**
n.a.

**Additional context**

**Comment by mswertz** [comment]
suggest we might ran out of connection pool somehow. Need ore information to reproduce.
