### ISSUE TITLE
Check on Tim's PR with Amer --> Br English  https://github.com/molgenis/molgenis-emx2/pull/3836

### ISSUE THREAD

**Issue by EleanorHyde-UMCG** [molgenis/molgenis-emx2#3852]
Tim's request: Hi all, I have a draft PR which is failing on CI - could a developer take a look for me? The intent was only to change language from American to British English, but maybe I changed some object names or something?

**Comment by dtroelofsprins** [comment]
@timcadman 
Several test Catalogue loaders fail:

TestLoaders > test2DataCatalogueLoader() FAILED
    Transaction failed: Upsert into table 'Datasets' failed: column 'name' is required in ROW(unit of observation='null' keywords='null' resource='testCohort1,test dataset for testCohort1,label for test dataset 1,Patient,"Social participation,Social environment and relationships,Social network,Social support,Parenting and familial environment,Family mental health,Other social environment characteristics",test description for dataset 1,30000,1959,1985' until version='null' name='null' description='null' number of rows='null' label='null' since version='null' mg_tableclass='catalogue.Datasets'): Upsert into table 'Datasets' failed: column 'name' is required in ROW(unit of observation='null' keywords='null' resource='testCohort1,test dataset for testCohort1,label for test dataset 1,Patient,"Social participation,Social environment and relationships,Social network,Social support,Parenting and familial environment,Family mental health,Other social environment characteristics",test description for dataset 1,30000,1959,1985' until version='null' name='null' description='null' number of rows='null' label='null' since version='null' mg_tableclass='catalogue.Datasets')
        at app//org.molgenis.emx2.sql.SqlDatabase.tx(SqlDatabase.java:550)
        at app//org.molgenis.emx2.sql.SqlSchema.tx(SqlSchema.java:174)
        at app//org.molgenis.emx2.datamodels.AbstractDataLoader.load(AbstractDataLoader.java:19)
        at app//org.molgenis.emx2.datamodels.AvailableDataModels.install(AvailableDataModels.java:31)
        at app//org.molgenis.emx2.datamodels.TestLoaders.test2DataCatalogueLoader(TestLoaders.java:64)

TestLoaders > test7DataCatalogueCohortStagingLoader() FAILED
    Transaction failed: Add column 'Variable mappings.target' failed: 'refTable' required for columns of type REF, REF_ARRAY, REFBACK (tried to find: catalogue:Extended resources): Add column 'Variable mappings.target' failed: 'refTable' required for columns of type REF, REF_ARRAY, REFBACK (tried to find: catalogue:Extended resources)
        at app//org.molgenis.emx2.sql.SqlDatabase.tx(SqlDatabase.java:550)
        at app//org.molgenis.emx2.sql.SqlSchema.tx(SqlSchema.java:174)
        at app//org.molgenis.emx2.datamodels.AbstractDataLoader.load(AbstractDataLoader.java:19)
        at app//org.molgenis.emx2.datamodels.AvailableDataModels.install(AvailableDataModels.java:31)
        at app//org.molgenis.emx2.datamodels.TestLoaders.test7DataCatalogueCohortStagingLoader(TestLoaders.java:78)

TestLoaders > test8DataCatalogueNetworkStagingLoader() FAILED
    Transaction failed: Create column 'Organisations.type' failed: refSchema 'CatalogueOntologies' does not exist or permission denied: Create column 'Organisations.type' failed: refSchema 'CatalogueOntologies' does not exist or permission denied
        at app//org.molgenis.emx2.sql.SqlDatabase.tx(SqlDatabase.java:550)
        at app//org.molgenis.emx2.sql.SqlSchema.tx(SqlSchema.java:174)
        at app//org.molgenis.emx2.datamodels.AbstractDataLoader.load(AbstractDataLoader.java:19)
        at app//org.molgenis.emx2.datamodels.AvailableDataModels.install(AvailableDataModels.java:31)
        at app//org.molgenis.emx2.datamodels.TestLoaders.test8DataCatalogueNetworkStagingLoader(TestLoaders.java:85)

**Comment by EleanorHyde-UMCG** [comment]
Potentially an issue with fieldnames being "British"-ised?

**Comment by EleanorHyde-UMCG** [comment]
See #3836

**Comment by EleanorHyde-UMCG** [comment]
@connoratrug in dev I don't see the new cohort contact page with the extra fields (which I do see in acc, with the "organization" spelling which needs changing to "organisation").

**Comment by EleanorHyde-UMCG** [comment]
Last piece, 'organisation' in cohort contact page, tested in acc. Can be closed.
