### ISSUE TITLE
Pattern matching MOLGENIS_POSTGRES_URI prevents connection to cloud hosted Postgres instances

### ISSUE THREAD

**Issue by dijansen** [molgenis/molgenis-emx2#520]
**What version of EMX2 are you using (see footer)**
molgenis-emx2 8.9.3

**Describe the bug**
Connecting to a Azure Database for PostgreSQL is not possible due to Molgenis' Postgres URI validation ([see here](https://github.com/molgenis/molgenis-emx2/blob/master/backend/molgenis-emx2-sql/src/main/java/org/molgenis/emx2/sql/SqlDatabase.java#L104))

**To Reproduce**
1. Set MOLGENIS_POSTGRES_URI to jdbc:postgresql://database-name.postgres.database.azure.com:5432/postgres
2. Fire up container (local or in cloud)
3. See error:
`2021-09-03_08:30:39.616 [main] ERROR org.molgenis.emx2.sql.SqlDatabase - Error: invalid MOLGENIS_POSTGRES_URI string. Found :jdbc:postgresql://database-name.postgres.database.azure.com:5432/postgres
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "javax.sql.DataSource.getConnection()" because "this.dataSource" is null
	at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:87)
	at org.molgenis.emx2.sql.SqlUserAwareConnectionProvider.acquire(SqlUserAwareConnectionProvider.java:24)
	at org.jooq.impl.DefaultTransactionProvider.connection(DefaultTransactionProvider.java:137)
	at org.jooq.impl.DefaultTransactionProvider.brace(DefaultTransactionProvider.java:238)
	at org.jooq.impl.DefaultTransactionProvider.begin(DefaultTransactionProvider.java:151)
	at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$0(DefaultDSLContext.java:537)
	at org.jooq.impl.Tools$35$1.block(Tools.java:5242)
	at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3137)
	at org.jooq.impl.Tools$35.get(Tools.java:5239)
	at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:595)
	at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:512)
	at org.jooq.impl.DefaultDSLContext.transaction(DefaultDSLContext.java:612)
	at org.molgenis.emx2.sql.SqlDatabase.init(SqlDatabase.java:128)
	at org.molgenis.emx2.sql.SqlDatabase.<init>(SqlDatabase.java:77)
	at org.molgenis.emx2.RunMolgenisEmx2.main(RunMolgenisEmx2.java:29)
	Suppressed: java.lang.NullPointerException: Cannot invoke "javax.sql.DataSource.getConnection()" because "this.dataSource" is null
		at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:87)
		at org.molgenis.emx2.sql.SqlUserAwareConnectionProvider.acquire(SqlUserAwareConnectionProvider.java:24)
		at org.jooq.impl.DefaultTransactionProvider.connection(DefaultTransactionProvider.java:137)
		at org.jooq.impl.DefaultTransactionProvider.brace(DefaultTransactionProvider.java:238)
		at org.jooq.impl.DefaultTransactionProvider.rollback(DefaultTransactionProvider.java:229)
		at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$0(DefaultDSLContext.java:567)
		... 9 more`

**Expected behavior**
Connection string is typically the responsibiliy of the developer/maintainer. I would expect to be able to connect Molgenis to anything.

**Additional context**

**Comment by dijansen** [comment]
On top of that, the error message is a bit tricky. The semicolon after 'Found' get prepended to the connection string :).

**Comment by dijansen** [comment]
@mswertz

**Comment by mswertz** [comment]
yes, sorry, was in bed with a fever. Agree with your suggestion, will push a fix today.
