### ISSUE TITLE
Theme not working under Windows

### ISSUE THREAD

**Issue by joerivandervelde** [molgenis/molgenis-emx2#757]
**What version of EMX2 are you using (see footer)**
molgenis-emx2-8.28.1-all.jar

**Describe the bug**
Server starts and app works but layout does not work because theme.scss cannot be loaded.

Stacktrace:

2021-11-30_11:22:37.450 [qtp1053973563-25] ERROR org.molgenis.emx2.web.MolgenisWebservice - SASS compilation failed: Error: java.io.FileNotFoundException: theme.scss
       java.lang.RuntimeException: java.io.FileNotFoundException: theme.scss
        at org.molgenis.emx2.web.BootstrapThemeService.doImport(BootstrapThemeService.java:164)
        at io.bit3.jsass.adapter.NativeImporterWrapper.apply(NativeImporterWrapper.java:39)
        at io.bit3.jsass.adapter.NativeAdapter.compileString(Native Method)
        at io.bit3.jsass.adapter.NativeAdapter.compile(NativeAdapter.java:55)
        at io.bit3.jsass.Compiler.compile(Compiler.java:114)
        at io.bit3.jsass.Compiler.compileString(Compiler.java:64)
        at io.bit3.jsass.Compiler.compileString(Compiler.java:47)
        at org.molgenis.emx2.web.BootstrapThemeService.generateCss(BootstrapThemeService.java:108)
        at org.molgenis.emx2.web.BootstrapThemeService.getCss(BootstrapThemeService.java:71)
        at spark.RouteImpl$1.handle(RouteImpl.java:72)
        at spark.http.matching.Routes.execute(Routes.java:61)
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1584)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:501)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
        at java.base/java.lang.Thread.run(Thread.java:833)
       Caused by: java.io.FileNotFoundException: theme.scss
        at org.molgenis.emx2.web.BootstrapThemeService.doImport(BootstrapThemeService.java:162)
        ... 31 more

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Firefox

**Comment by chinook25** [comment]
Fixed with https://github.com/molgenis/molgenis-emx2/pull/971
